# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 374e74d5e5fa8eb7bd505ffae45cba2a70ee760e95dcf9abce5b2c23830a72ddc581f6e32a5a6fed8d41ed6b8f9d057f1e498867b7c3a73dab1a56654dc0c4f1

test:
  secret_key_base: 353842c85a8a22dc228b4831078d056ec2c35710afc1a433894ccf66dc5c68e921d4c845e0710bb8470baaa694380cd2220a8576282f9404f1a9aec7dd2c830a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
